# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "almalinux/8"

  config.vm.hostname = "lamp74"
  
  config.vm.network :private_network, ip: '192.168.33.126'
  config.vm.network :forwarded_port, guest: 22, host: 2222, id: "ssh", auto_correct: true

  config.vm.synced_folder ".", "/home/vagrant/sync", disabled: true
  config.vm.synced_folder "../", "/vagrant", type: "virtualbox",
                          :mount_options => ["dmode=777", "fmode=777"]

  if Vagrant.has_plugin?("vagrant-vbguest")
    config.vbguest.auto_update = false
  end

  config.vm.provider "virtualbox" do |vb|
    vb.customize ["modifyvm", :id, "--name", "lamp74"]
    vb.memory = "1536"
  end

  config.vm.provision "docker"

  config.vm.provision "shell", inline: <<-SHELL
    sudo dnf -y update kernel
    sudo dnf -y install gcc kernel-devel kernel-headers make bzip2 perl
  SHELL
end