version: '3'

services:
  mysql:
    # hub.docker.com からイメージを取得する
    build:
      context: ./mysql
      # Dockerfile に .env の変数を渡す
      args:
        MYSQL_USER: ${MYSQL_USER}
        MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    # MySQL設定
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
#    ports:
#      - "13306:3306"
#      - "13360:33060"
    volumes:
      - mysql-data:/var/lib/mysql
      - mysql-log:/var/log/mysql
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    restart: always
    networks:
      app_net:
        ipv4_address: 172.18.0.11
  
  php80_apache:
    build:
      context: ./php80-apache
    volumes:
      - ../code:/var/www/code
    restart: always
    links:
      - mysql
    ports:
      - "80:80"
    networks:
      app_net:

networks:
  app_net:
    name: app_net
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/24

volumes:
  mysql-data:
  mysql-log: